apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/httproute-frontend.yaml
  - manifests/target-grp-frontend.yaml
helmCharts:
  - name: onlineboutique
    repo: oci://ghcr.io/ibtisam-iq
    version: 0.10.5
    releaseName: boutique-app
    namespace: boutique-app
    valuesFile: chart/values-eks.yaml
    