# k8s/overlays/bare-metal/httproute.yaml
# HTTPRoute for bankapp-service

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bankapp-route
  namespace: bankapp
  labels:
    app.kubernetes.io/name: bankapp
    app.kubernetes.io/component: routing
spec:
  parentRefs:
    - name: bankapp-gateway
      namespace: bankapp
      sectionName: https
  hostnames:
  - java-monolith.ibtisam-iq.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: bankapp-service
          port: 80
          weight: 100

---
# HTTP to HTTPS Redirect
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bankapp-http-redirect
  namespace: bankapp
spec:
  parentRefs:
    - name: bankapp-gateway
      namespace: bankapp
      sectionName: http
  hostnames:
    - java-monolith.ibtisam-iq.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
