# k8s/overlays/bare-metal/kustomization.yaml
# Bare-metal Kustomize Overlay
# Environment: bare-metal / minikube / kind

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bankapp

resources:
  - ../../base
  # Ingress-based routing (uncomment to use)
  # - ingress.yaml
  # - ingress-cert.yaml
  # Gateway API-based routing (active)
  - gateway-cert.yaml
  - httproute.yaml

patches:
  - path: patch-storageclass.yaml
  - path: patch-service-nodeport.yaml

images:
  - name: mibtisam/java-monolith
    newName: mibtisam/java-monolith
    newTag: latest

labels:
  - pairs:
      environment: bare-metal
    includeSelectors: true
    includeTemplates: true
