# k8s/overlays/bare-metal/patch-service-nodeport.yaml
# Converts bankapp-service from ClusterIP to NodePort.

apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: bankapp
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      protocol: TCP
