# k8s/base/configmap.yaml
# Non-sensitive application configuration for BankApp.
# Managed by: Kustomize

apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp
  labels:
    app.kubernetes.io/name: bankapp
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: java-monolith
    app.kubernetes.io/managed-by: kustomize
data:
  SPRING_APPLICATION_NAME: "IbtisamIQBankApp"
  MYSQL_DATABASE: "IbtisamIQbankappdb"
  SERVER_PORT: "8000"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service.bankapp.svc.cluster.local:3306/IbtisamIQbankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
