# k8s/base/kustomization.yaml
# Base Kustomize configuration for BankApp.
# Managed by: Kustomize

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bankapp

commonAnnotations:
  config.kubernetes.io/origin: "platform-engineering-systems/systems/java-monolith/k8s/base"
  gitops/managed-by: "kustomize-cli"

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: java-monolith
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true

images:
  - name: mibtisam/java-monolith
    newName: mibtisam/java-monolith
    newTag: "latest"
