# k8s/base/mysql-service.yaml
# ClusterIP Service for MySQL
# Managed by: Kustomize

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: bankapp
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: java-monolith
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: mysql
