# k8s/base/namespace.yaml
# Namespace for the BankApp deployment.
# Managed by: Kustomize

apiVersion: v1
kind: Namespace
metadata:
  name: bankapp
  labels:
    app.kubernetes.io/name: bankapp
    app.kubernetes.io/part-of: java-monolith
    app.kubernetes.io/managed-by: kustomize
